# Generated by Django 3.0.5 on 2020-04-25 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_auto_20200425_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('pages', models.IntegerField(null=True)),
                ('no_of_copies', models.IntegerField()),
                ('published_date', models.DateField(default=datetime.date(2020, 4, 25), null=True)),
            ],
        ),
    ]
