# Generated by Django 3.0.5 on 2020-04-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_auto_20200425_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publication_house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libapp.PublicationHouse'),
            preserve_default=False,
        ),
    ]
