# Generated by Django 3.0.5 on 2020-05-03 15:33

from django.db import migrations, models
import django.db.models.deletion
import libapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_auto_20200503_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profilepicpath',
            field=models.ImageField(blank=True, null=True, upload_to=libapp.models.upload_profile_pic),
        ),
        migrations.CreateModel(
            name='BooksIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='students',
            field=models.ManyToManyField(through='libapp.BooksIssued', to='libapp.Student'),
        ),
    ]
